import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


// import Dummmy from '../components/dummmy'

export default function Home() {
  return (
   
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:30px
        }
        h3{
          font-size:23px
        }
        `}
      </style>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='span dummy'> Blogging</span>
        </h1>
        <div className={styles.imgwrap}>
        <Image className={styles.myImg} src="/home.jpg"  width={237} height={158}/>
        </div>

        <p className={styles.description}>
         coders blog
       
        </p>
        {/* <Dummmy/> */}

       <div className="blogs">
        <h2>Popular Blogs</h2>
        <div className="blogItem">
          <h3>How to learn Next</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipoptio.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn Next</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipoptio.</p>
        </div>
       </div>

      
      </main>

      
    </div>
  )
}
